spring:
  application:
    name: ead-authuser-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      ## Usuário e Senha para logar no config-server
      username: configserver
      password: '123456'
