server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MateusBraz/ead-config-server
          default-label: main
          username: MateusBraz
#          password: ***********

ead:
  configServer:
    username: configserver
    password: '123456'
  serviceRegistry:
    username: serviceregistry
    password: '123456'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost